### ISSUE TITLE
got error like this when i try to add card in todo list 

### ISSUE THREAD

**Issue by Aadesh2003** [desi-programmer/fluttertodo#2]
TypeError: Cannot read properties of null (reading 'insert')
at insert (http://localhost:64355/packages/todo/dbhelper.dart.lib.js:52:25)
    at insert.next (<anonymous>)
    at http://localhost:64355/dart_sdk.js:40646:33
    at _RootZone.runUnary (http://localhost:64355/dart_sdk.js:40503:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:64355/dart_sdk.js:35432:29)
    at handleValueCallback (http://localhost:64355/dart_sdk.js:36017:49)
    at Function._propagateToListeners (http://localhost:64355/dart_sdk.js:36055:17)
    at _Future.new.[_completeWithValue] (http://localhost:64355/dart_sdk.js:35897:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64355/dart_sdk.js:35920:35)
    at Object._microtaskLoop (http://localhost:64355/dart_sdk.js:40808:13)
    at _startMicrotaskLoop (http://localhost:64355/dart_sdk.js:40814:13)
    at http://localhost:64355/dart_sdk.js:36279:9

**Comment by desi-programmer** [comment]
Can You Post Mode Details ?? 

Where it occurred ?
Flutter version ?
